### ISSUE TITLE
Why are all requests to rollbar going through the server?

### ISSUE THREAD

**Issue by andylash** [thesaucecode/meteor-rollbar#7]
Maybe there's something I'm not considering.  I've used rollbar and meteor together for a while now.  Not sure why you're not connecting to rollbar directly, but going through the server.  I guess you can the user's name, but you can also just send that to rollbar with each request.  Just not seeing what the extra complexity buys you.  

thanks,
andy

**Comment by rjerrems** [comment]
Hi Andy -  Initially one of the drivers for this was so that you would not need to expose your Rollbar api key on the client side. It's no longer quite as relevant now that we have implemented the client side javascript (initially we were just using the NPM package server side).

The handleError() and throwError() methods are provided for convenience and will add information about the current user and http headers where available automatically. If you would prefer not to use them, you can access Rollbar through the exposed namespace rollbar on the server side.

If you have any ideas about how we can improve the package, I would be happy to hear them or you can just create a pull request if you want.

Thanks,
Rohan

**Comment by em0ney** [comment]
Hi @andylash 

Having the same method name for client and server means that you can write truly isomorphic code.  I.e. you don't need to worry whether you are on the client or server, you write the same error handling.

We also have the browserJS rollbar available, so you can log errors through that if you so wish.

Elliott
